document:
  type: Linee guida
  name: Statistiche SPID
  short_name: Ll.gg. Statistiche SPID
  author: walter-arrighetti
  contributors:
    - Gabriele Bocchetta
    - Stefano Arbia
    - Antonio Florio
    - Michele d'Amico
    - Stefano Ianniello
    - Andrea Spallacci
    - Walter Arrighetti
  description: |
    Linee Guida contenenti le Regole Tecniche per le Statistiche SPID
  tags:
    - SPID
    - eIDAS
    - 
    - 
    - 
    - 
    - 
  origin: https://github.com/AgID/lg-spid-statistiche-docs
